package com.greninjaop.mailorganizer.core.cleanup

import com.greninjaop.mailorganizer.core.classify.Confidence
import com.greninjaop.mailorganizer.data.local.MailCategory
import com.greninjaop.mailorganizer.data.local.Priority

/**
 * Deterministic Noise & Low-Value Email Intelligence (Phase 20 §16–§19, §23).
 *
 * Distinguishes:
 * - Notification: Automated message generated by a system.
 * - Promotion: Marketing / commercial communication.
 * - Noise: Low practical value based on evidence.
 * - Low value: An intelligence judgment, NOT an automatic deletion license.
 *
 * Low interaction alone NEVER means safe to delete.
 */
object NoiseAnalyzer {

    const val VERSION = 1

    private val NOTIFICATION_SUBJECT_KEYWORDS = listOf(
        "notification",
        "alert",
        "no-reply",
        "noreply",
        "system update",
        "terms of service",
        "privacy policy update",
        "automated message",
        "status update",
        "build succeeded",
        "build failed",
        "new sign-in", // Note: protected if security, but matches notification format
    )

    private val NOTIFICATION_SENDER_PATTERNS = listOf(
        "noreply@",
        "no-reply@",
        "notifications@",
        "donotreply@",
        "mailer-daemon@",
        "system@",
        "alerts@",
    )

    fun analyze(input: CleanupAnalysisInput): NoiseAnalysisResult {
        val isProtected = CleanupProtector.isShielded(
            category = input.category,
            priority = input.priority,
            starred = input.starred,
            hasActionItem = input.hasActionItem,
        )

        val protectionReason = CleanupProtector.protectionReason(
            category = input.category,
            priority = input.priority,
            starred = input.starred,
            hasActionItem = input.hasActionItem,
        )

        val reasons = mutableListOf<String>()

        if (isProtected) {
            if (protectionReason != null) {
                reasons.add(protectionReason)
            }
            return NoiseAnalysisResult(
                isNoise = false,
                isLowValue = false,
                isProtected = true,
                confidence = Confidence.HIGH,
                explanation = NoiseExplanation(
                    isProtectedCategory = CleanupProtector.isProtectedCategory(input.category),
                    isProtectedPriority = CleanupProtector.isProtectedPriority(input.priority),
                    isActionRequired = input.hasActionItem || input.category == MailCategory.ACTION_REQUIRED,
                    reasonsSummary = reasons,
                ),
                version = VERSION,
            )
        }

        // Automated notification detection
        val fromLower = input.senderAddress.lowercase()
        val subjectLower = input.subject.lowercase()

        val isAutomatedSender = NOTIFICATION_SENDER_PATTERNS.any { fromLower.contains(it) }
        val isAutomatedSubject = NOTIFICATION_SUBJECT_KEYWORDS.any { subjectLower.contains(it) }
        val isCategoryNotification = input.category == MailCategory.NOTIFICATIONS
        val isCategoryLowValue = input.category == MailCategory.LOW_VALUE
        val isCategoryPromotions = input.category == MailCategory.PROMOTIONS

        var noiseScore = 0

        if (isAutomatedSender) {
            noiseScore += 25
            reasons.add("Automated or no-reply sender address")
        }
        if (isAutomatedSubject) {
            noiseScore += 20
            reasons.add("Notification / status subject pattern")
        }
        if (isCategoryNotification) {
            noiseScore += 30
            reasons.add("Classified as Notification")
        }
        if (isCategoryPromotions) {
            noiseScore += 25
            reasons.add("Classified as Promotion")
        }
        if (isCategoryLowValue) {
            noiseScore += 45
            reasons.add("Classified as Low Value")
        }
        if (input.priority == Priority.LOW) {
            noiseScore += 20
            reasons.add("Low priority mail")
        }
        if (input.isRecurringSender && input.senderMessageCount >= 5) {
            noiseScore += 10
            reasons.add("High-frequency recurring sender (${input.senderMessageCount} emails)")
        }

        val isLowValue = isCategoryLowValue || (noiseScore >= 50 && input.priority == Priority.LOW)
        val isNoise = noiseScore >= 45

        val confidence = when {
            noiseScore >= 65 -> Confidence.HIGH
            noiseScore >= 45 -> Confidence.MEDIUM
            else -> Confidence.LOW
        }

        return NoiseAnalysisResult(
            isNoise = isNoise,
            isLowValue = isLowValue,
            isProtected = false,
            confidence = confidence,
            explanation = NoiseExplanation(
                isAutomatedNotification = isAutomatedSender || isAutomatedSubject || isCategoryNotification,
                isPromotional = isCategoryPromotions,
                isRecurringLowValue = input.isRecurringSender && isLowValue,
                isOldUnread = input.unread && (System.currentTimeMillis() - input.timestampEpochMs > 30L * 24 * 3600 * 1000),
                isProtectedCategory = false,
                isProtectedPriority = false,
                isActionRequired = false,
                reasonsSummary = reasons,
            ),
            version = VERSION,
        )
    }
}
